[2023-10-05 19:39:16,590] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-03T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:39:16,602] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-03T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:39:16,603] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:39:16,604] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:39:16,605] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:39:16,630] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2023-10-03 19:32:37.598184+00:00
[2023-10-05 19:39:16,637] {standard_task_runner.py:52} INFO - Started process 2216 to run task
[2023-10-05 19:39:16,641] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'scheduled__2023-10-03T19:32:37.598184+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpfmuied5f', '--error-file', '/tmp/tmph79n8ztu']
[2023-10-05 19:39:16,642] {standard_task_runner.py:80} INFO - Job 57: Subtask update_d_customer
[2023-10-05 19:39:16,721] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-03T19:32:37.598184+00:00 [running]> on host 8305c4468fa5
[2023-10-05 19:39:16,812] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T19:32:37.598184+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T19:32:37.598184+00:00
[2023-10-05 19:39:16,827] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-05 19:39:16,835] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2023-10-05 19:39:16,841] {sql.py:324} INFO - Rows affected: 269
[2023-10-05 19:39:16,870] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20231003T193237, start_date=20231005T193916, end_date=20231005T193916
[2023-10-05 19:39:16,896] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-05 19:39:16,955] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
