[2023-10-05 19:39:39,357] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales scheduled__2023-10-04T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:39:39,375] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales scheduled__2023-10-04T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:39:39,376] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:39:39,376] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:39:39,377] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:39:39,400] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_sales> on 2023-10-04 19:32:37.598184+00:00
[2023-10-05 19:39:39,405] {standard_task_runner.py:52} INFO - Started process 2386 to run task
[2023-10-05 19:39:39,408] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_f_sales', 'scheduled__2023-10-04T19:32:37.598184+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmps2tqco54', '--error-file', '/tmp/tmp7fne4_jo']
[2023-10-05 19:39:39,410] {standard_task_runner.py:80} INFO - Job 64: Subtask update_f_sales
[2023-10-05 19:39:39,500] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_f_sales scheduled__2023-10-04T19:32:37.598184+00:00 [running]> on host 8305c4468fa5
[2023-10-05 19:39:39,603] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_f_sales
AIRFLOW_CTX_EXECUTION_DATE=2023-10-04T19:32:37.598184+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-04T19:32:37.598184+00:00
[2023-10-05 19:39:39,618] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-05 19:39:39,627] {sql.py:315} INFO - Running statement: insert into mart.f_sales (date_id, item_id, customer_id, city_id, quantity, payment_amount,"status")
select 
    dc.date_id
    ,uol.item_id
    ,uol.customer_id
    ,uol.city_id
    ,uol.quantity
    ,case 
        when uol."status" = 'refunded'
        then -uol.payment_amount 
        else uol.payment_amount 
    end as payment_amount
    ,uol."status"
from staging.user_order_log uol
left join mart.d_calendar as dc on uol.date_time::Date = dc.date_actual
where uol.date_time::Date = '2023-10-04';, parameters: {'date': ('{{ ds }}',)}
[2023-10-05 19:39:39,652] {sql.py:324} INFO - Rows affected: 451
[2023-10-05 19:39:39,694] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_f_sales, execution_date=20231004T193237, start_date=20231005T193939, end_date=20231005T193939
[2023-10-05 19:39:39,742] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-05 19:39:39,790] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
