[2023-10-05 19:28:01,901] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:26:20.389129+00:00 [queued]>
[2023-10-05 19:28:01,911] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:26:20.389129+00:00 [queued]>
[2023-10-05 19:28:01,912] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:28:01,912] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:28:01,913] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:28:01,938] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-09-27 19:26:20.389129+00:00
[2023-10-05 19:28:01,947] {standard_task_runner.py:52} INFO - Started process 902 to run task
[2023-10-05 19:28:01,950] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'scheduled__2023-09-27T19:26:20.389129+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmptrmd9893', '--error-file', '/tmp/tmppuumbco0']
[2023-10-05 19:28:01,952] {standard_task_runner.py:80} INFO - Job 10: Subtask get_increment
[2023-10-05 19:28:02,017] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:26:20.389129+00:00 [running]> on host 329f0cdeb700
[2023-10-05 19:28:02,105] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-09-27T19:26:20.389129+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-27T19:26:20.389129+00:00
[2023-10-05 19:28:02,106] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-05 19:28:02,322] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3lOam96T0Fsc2EyNWZjRzl3YjNZPQ==","date":"2023-09-27 00:00:00","status":"NOT FOUND","data":{"increment_id":null},"debug_info":"Date is too early. You need specify the date greater then date in the general report."}'
[2023-10-05 19:28:02,323] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 76, in get_increment
    raise ValueError(f'Increment is empty. Most probably due to error in API call.')
ValueError: Increment is empty. Most probably due to error in API call.
[2023-10-05 19:28:02,341] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20230927T192620, start_date=20231005T192801, end_date=20231005T192802
[2023-10-05 19:28:02,357] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task get_increment (Increment is empty. Most probably due to error in API call.; 902)
[2023-10-05 19:28:02,367] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 19:28:02,424] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
