[2023-10-07 08:23:20,177] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-02T08:17:37.691037+00:00 [queued]>
[2023-10-07 08:23:20,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-02T08:17:37.691037+00:00 [queued]>
[2023-10-07 08:23:20,184] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:23:20,185] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 08:23:20,185] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:23:20,193] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2023-10-02 08:17:37.691037+00:00
[2023-10-07 08:23:20,196] {standard_task_runner.py:52} INFO - Started process 1917 to run task
[2023-10-07 08:23:20,198] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'scheduled__2023-10-02T08:17:37.691037+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmph4x7oyfb', '--error-file', '/tmp/tmpw0db9qbq']
[2023-10-07 08:23:20,199] {standard_task_runner.py:80} INFO - Job 50: Subtask update_d_customer
[2023-10-07 08:23:20,238] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer scheduled__2023-10-02T08:17:37.691037+00:00 [running]> on host 36d9c57a9c84
[2023-10-07 08:23:20,278] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T08:17:37.691037+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T08:17:37.691037+00:00
[2023-10-07 08:23:20,285] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-07 08:23:20,289] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2023-10-07 08:23:20,291] {sql.py:324} INFO - Rows affected: 61
[2023-10-07 08:23:20,301] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20231002T081737, start_date=20231007T082320, end_date=20231007T082320
[2023-10-07 08:23:20,331] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-07 08:23:20,355] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
