[2023-10-07 12:57:13,587] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2023-10-07T12:55:56.754911+00:00 [queued]>
[2023-10-07 12:57:13,593] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2023-10-07T12:55:56.754911+00:00 [queued]>
[2023-10-07 12:57:13,594] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:57:13,595] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 12:57:13,595] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:57:13,605] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2023-10-07 12:55:56.754911+00:00
[2023-10-07 12:57:13,608] {standard_task_runner.py:52} INFO - Started process 3889 to run task
[2023-10-07 12:57:13,610] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'manual__2023-10-07T12:55:56.754911+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpwqmq6kgz', '--error-file', '/tmp/tmploon6yj6']
[2023-10-07 12:57:13,610] {standard_task_runner.py:80} INFO - Job 106: Subtask update_d_customer
[2023-10-07 12:57:13,650] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer manual__2023-10-07T12:55:56.754911+00:00 [running]> on host d964b2b568e5
[2023-10-07 12:57:13,694] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T12:55:56.754911+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T12:55:56.754911+00:00
[2023-10-07 12:57:13,702] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-07 12:57:13,706] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2023-10-07 12:57:13,708] {sql.py:324} INFO - Rows affected: 0
[2023-10-07 12:57:13,718] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20231007T125556, start_date=20231007T125713, end_date=20231007T125713
[2023-10-07 12:57:13,743] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-07 12:57:13,769] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
